### ISSUE TITLE
Podman used in ec2 instance cloud config before podman is installed

### ISSUE THREAD

**Issue by dmc5179** [openshift/quay-image-builder#31]
The cloud-config.sh script has been switched to use the aws CLI container instead of using the python3 pip module. As a result, podman is used in the cloud-config.sh script but podman is not installed on the host until the bootstrap playbook is run.

Testing was done using aws-rhel8-quay.json and no other base AMI.

Need to update the cloud-config.sh script to install podman before using it in the script.

**Comment by bparry02** [comment]
The cloud-config.sh installs podman before running any AWS CLI commands here:
https://github.com/openshift/quay-image-builder/blob/main/cloud-config.sh.template#L76
