### ISSUE TITLE
AWS CLI convenience container results in hard coded repo values

### ISSUE THREAD

**Issue by dmc5179** [openshift/quay-image-builder#32]
Using the AWS CLI convenience container, instead of simply installing the awscli pip module, requires that yum repos be configured in the cloud-config.sh script. This has lead to several issues:

- The repos configured in the cloud-config.sh script are hard coded to use OCP 4.13. T here is no sed command used to ensure the repos match the version of OpenShift being built by the packer build.

- The build.sh file already uses the quay_image.repo file and sed to configure the repos in the EC2 instance user data script on boot

Need to remove the quay_image.repo config from the cloud-config.sh script since they are already correctly configured by the build.sh script for use in the EC2 user data script.

**Comment by bparry02** [comment]
The build.sh is responsible for taking the content of quay_image.repo and [in-lining it to the cloud-config.sh](https://github.com/openshift/quay-image-builder/blob/main/build.sh#L149) script. Then, the build.sh [replaces the OCP version placeholders](https://github.com/openshift/quay-image-builder/blob/main/build.sh#L151) everywhere they are found in the cloud-config.sh script. Finally, the build.sh launches packer which creates an AMI using the cloud-config as user data. The repos should be correctly configured at that point.

**Comment by bparry02** [comment]
Closing stale issue
